// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkLZ9CUMSR0HhoTQ1xJbVjvRbS_jNuyOs',
    appId: '1:15944371985:web:2834b4336cf818848246b0',
    messagingSenderId: '15944371985',
    projectId: 'dashboard-a2ac9',
    authDomain: 'dashboard-a2ac9.firebaseapp.com',
    storageBucket: 'dashboard-a2ac9.appspot.com',
    measurementId: 'G-YECY9EL7DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURRV-S9OeUH-yYemgwCy551FdI5ra1vM',
    appId: '1:15944371985:android:af0841fad21316558246b0',
    messagingSenderId: '15944371985',
    projectId: 'dashboard-a2ac9',
    storageBucket: 'dashboard-a2ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVvcc2QVOBUh9-6UvEHfgBLYCyipFxq-M',
    appId: '1:15944371985:ios:2a884b60986004ef8246b0',
    messagingSenderId: '15944371985',
    projectId: 'dashboard-a2ac9',
    storageBucket: 'dashboard-a2ac9.appspot.com',
    iosBundleId: 'com.example.dashboardTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVvcc2QVOBUh9-6UvEHfgBLYCyipFxq-M',
    appId: '1:15944371985:ios:e8c3ed756c98715f8246b0',
    messagingSenderId: '15944371985',
    projectId: 'dashboard-a2ac9',
    storageBucket: 'dashboard-a2ac9.appspot.com',
    iosBundleId: 'com.example.dashboardTask.RunnerTests',
  );
}
